version: '3.8'

services:
  db:
    image: postgres:16
    container_name: post_office_db
    environment:
      POSTGRES_DB: post-office
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajlksdhxfkjlahsdfjk

    ports:
      - "5432:5432"

    volumes:
      - /post_office_db:/var/lib/postgresql/data

