version: '3.8'

services:

  post-office-app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: post-office-app
    container_name: post-office-app
    depends_on:
      - db
    ports:
      - "8080:8080"

  flyway:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: flyway
    container_name: flyway
    depends_on:
      - db
    ports:
      - "8100:8100"

  db:
    image: postgres:16
    container_name: post_office_db
    restart: always
    environment:
      POSTGRES_DB: post-office
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajlksdhxfkjlahsdfjk

    ports:
      - "5432:5432"

    volumes:
      - post_office_db:/var/lib/postgresql/data

volumes:
  post_office_db:
  
